const UserActionTypes = {
  LOGIN_USER: "LOGIN_USER",
  ADD_SPENT: "ADD_SPENT",
  REPEAT_SPENT: "REPEAT_SPENT",
  DEL_SPENT: "DEL_SPENT",
  ADD_TAGS: "ADD_TAGS",
  DEL_TAG: "DEL_TAG",
  EMPTY_TAGS: "EMPTY_TAGS",
  ADD_CATTS: "ADD_CATTS",
  EMPTY_CATTS: "EMPTY_CATTS",
  DEL_CATT: "DEL_CATT",
  ADD_SEARCH: "ADD_SEARCH",
  EMPTY_SEARCH: "EMPTY_SEARCH",
};

export default UserActionTypes;
